theme = "alagyn"

[editor]
scrolloff = 8
completion-timeout = 100
bufferline = "always"
color-modes = true
continue-comments = false
# line-number = "relative"
popup-border = "all"
cursorline = true

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "warning"

[editor.statusline]
# mostly default, added version-control
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "spacer", "version-control"]
# Added file-indent-style
right = ["file-indent-style", "spacer", "diagnostics", "selections", "register", "position", "file-encoding"]

[editor.indent-guides]
render = true

[editor.whitespace.render]
tab = "all"
space = "all"

[editor.whitespace.characters]
space = "·"
tab = "→"
tabpad = "·" 
# Tabs will look like "→···" (depending on tab width)

[keys.normal]
C-g = [
    ":write-all",
    ":insert-output lazygit >/dev/tty",
    ":redraw",
    ":reload-all",
   ':set mouse false',
   ':set mouse true'
]
